import NextHead from 'next/head';
import { memo } from 'react';

function HeadComponent() {
  return (
    <NextHead>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </NextHead>
  );
}

export const Head = memo(HeadComponent);
